C:\Users\Daniil\Documents\GitHub\YellowSubmarineSolidworks\Lab1_Redo\Simulation\FloorPlatformAsm-Fatigue Static
C:\Users\Daniil\Documents\GitHub\YellowSubmarineSolidworks\Lab1_Redo\Simulation\FloorPlatformAsm-Fatigue Static
C:\Users\Daniil\Documents\GitHub\YellowSubmarineSolidworks\Lab1_Redo\Simulation\FloorPlatformAsm-Fatigue Static
C:\Users\Daniil\Documents\GitHub\YellowSubmarineSolidworks\Lab1_Redo\Simulation\FloorPlatformAsm-Fatigue Static
